System.Console.WriteLine("======Treino de C#======");
// EstruturaWhile.Executar();
// EstruturaFor.Executar();
//SwitchCase.Executar();
// OperadoresLogicos.Executar();
// Conversao.Executar();
//  Operadores.Executar();
// TrabalhandoComStrings.Executar();
//  Buscas.Executar();
// ArrayListas.Executar();
ArraysListasPratica.Executar();
